export const cartActionTypes = {
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CREATE_CHECK_OUT: 'CREATE_CHECK_OUT',
  UPDATE_CHECK_OUT: 'UPDATE_CHECK_OUT',
  REMOVE_ITEM_FROM_CHECKOUT: 'REMOVE_ITEM_FROM_CHECKOUT',
  CHECK_INVENTORY_QUANTITY: 'CHECK_INVENTORY_QUANTITY',
  RESET_CART: 'RESET_CART'
}
