const productActionTypes = {
  SET_DROP_PRODUCTS_START: 'SET_DROP_PRODUCTS_START',
  SET_DROP_PRODUCTS_SUCCESS: 'SET_DROP_PRODUCTS_SUCCESS',
  SET_DROP_PRODUCTS_FAILURE: 'SET_DROP_PRODUCTS_FAILURE',
  SET_CHOSEN_PRODUCT: 'SET_CHOSEN_PRODUCT'

}

export default productActionTypes;
